export const categories = [
  {
    id: "1",
    name: "Baby",
    slug: "baby",
    popularity: 125,
  },
  {
    id: "2",
    name: "Family",
    slug: "family",
    popularity: 35,
  },
  {
    id: "3",
    name: "Pet",
    slug: "pet",
    popularity: 0,
  },
  {
    id: "4",
    name: "Wedding",
    slug: "wedding",
    popularity: 300,
  },
  {
    id: "5",
    name: "Advertising",
    slug: "advertising",
    popularity: 0,
  },
  {
    id: "6",
    name: "Food",
    slug: "food",
    popularity: 0,
  },
  {
    id: "7",
    name: "Event",
    slug: "event",
    popularity: 0,
  },
  {
    id: "8",
    name: "Apparel & Textile",
    slug: "apparel-and-textile",
    popularity: 0,
  },
  {
    id: "9",
    name: "Corporate",
    slug: "corporate",
    popularity: 0,
  },
  {
    id: "10",
    name: "Fashion",
    slug: "fashion",
    popularity: 111,
  },
  {
    id: "11",
    name: "Photojournalist",
    slug: "photojournalist",
    popularity: 0,
  },
  {
    id: "12",
    name: "Action/Sport",
    slug: "action-sport",
    popularity: 0,
  },
  {
    id: "13",
    name: "School",
    slug: "school",
    popularity: 0,
  },
  {
    id: "14",
    name: "Travel",
    slug: "travel",
    popularity: 158,
  },
  {
    id: "15",
    name: "Real Estate & Architecture",
    slug: "real-estate-and-architecture",
    popularity: 0,
  },
  {
    id: "16",
    name: "Landscape",
    slug: "landscape",
    popularity: 0,
  },
  {
    id: "17",
    name: "Aerial",
    slug: "aerial",
    popularity: 0,
  },
  {
    id: "18",
    name: "Wildlife",
    slug: "wildlife",
    popularity: 256,
  },
  {
    id: "19",
    name: "Concert",
    slug: "concert",
    popularity: 0,
  },
  {
    id: "20",
    name: "Glamour",
    slug: "glamour",
    popularity: 47,
  },
  {
    id: "21",
    name: "Under-water",
    slug: "under-water",
    popularity: 0,
  },
  {
    id: "22",
    name: "Stock",
    slug: "stock",
    popularity: 0,
  },
  {
    id: "23",
    name: "Equine",
    slug: "equine",
    popularity: 0,
  },
  {
    id: "24",
    name: "Paparazzi",
    slug: "paparazzi",
    popularity: 0,
  },
  {
    id: "25",
    name: "Street",
    slug: "street",
    popularity: 45,
  },
  {
    id: "26",
    name: "Potrait Artist",
    slug: "potrait-artist",
    popularity: 0,
  },
];

export const photographer = {
  id: 1,
  code: "f6ykjas",
  name: "Guy Next Door",
  categories: "Wedding photographer",
  location: "Nairobi, Kenya",
  works: "Full Time",
  rate_min: 600,
  rate_max: 1200,
  negotiability: true,
  bookmarks: 35,
  bio: "Lorem Ipsum is simply dummy text of printing and type setting industry. Lorem Ipsum been industry standard dummy text ever since, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum",
  workdays: [
    { day: "Monday", time: "8am - 8pm" },
    { day: "Tuesday", time: "8am - 8pm" },
    { day: "Wednesday", time: "8am - 8pm" },
    { day: "Thursday", time: "8am - 8pm" },
    { day: "Friday", time: "8am - 8pm" },
    { day: "Saturday", time: "9am - 4pm" },
    { day: "Sunday", time: "Closed" },
  ],
  additional_packages: [
    { price: "Ksh 3,000", desc: "Drown photography" },
    { price: "Ksh 10,000", desc: "Additional lights" },
    { price: "Ksh 15,000", desc: "Wide Lens" },
    { price: "Ksh 1,000", desc: "Additonal imaging props" },
  ],
};

export const photographers = [
  {
    id: 1,
    code: "f6ykjas",
    name: "Guy Next Door",
    categories: "Wedding",
    category_id: 1,
    location: "Nairobi, Kenya",
    rate_min: 600,
    rate_max: 1200,
    negotiability: true,
  },
  {
    id: 2,
    code: "abv76t",
    name: "Sam Photo Lab",
    categories: "Wedding",
    category_id: 1,
    location: "Nairobi, Kenya",
    rate_min: 600,
    rate_max: 1200,
    negotiability: true,
  },
  {
    id: 3,
    code: "mli9h8",
    name: "Mulinge Photography",
    categories: "Wedding",
    category_id: 1,
    location: "Nairobi, Kenya",
    rate_min: 600,
    rate_max: 1200,
    negotiability: true,
  },
  {
    id: 4,
    code: "acvg6u",
    name: "Warui Studios",
    categories: "Wedding",
    category_id: 1,
    location: "Nairobi, Kenya",
    rate_min: 600,
    rate_max: 1200,
    negotiability: true,
  },
  {
    id: 5,
    code: "svhg7k",
    name: "Lex Photography",
    categories: "Wedding",
    category_id: 1,
    location: "Nairobi, Kenya",
    rate_min: 600,
    rate_max: 1200,
    negotiability: true,
  },
  {
    id: 6,
    code: "nmki78",
    name: "Studio Masters",
    categories: "Wedding",
    category_id: 1,
    location: "Mombasa, Kenya",
    rate_min: 600,
    rate_max: 1200,
    negotiability: true,
  },
  {
    id: 7,
    code: "hju889",
    name: "Mulinge Photography",
    categories: "Wedding",
    category_id: 1,
    location: "Kisii, Kenya",
    rate_min: 600,
    rate_max: 1200,
    negotiability: true,
  },
  {
    id: 8,
    code: "po09ii",
    name: "Warui Studios",
    categories: "Wedding",
    category_id: 1,
    location: "Kakamega, Kenya",
    rate_min: 600,
    rate_max: 1200,
    negotiability: true,
  },
  {
    id: 9,
    code: "klii90",
    name: "Lex Photography",
    categories: "Wedding",
    category_id: 1,
    location: "Nakuru, Kenya",
    rate_min: 600,
    rate_max: 1200,
    negotiability: true,
  },
  {
    id: 10,
    code: "cvuyi2",
    name: "Studio Masters",
    categories: "Wedding",
    category_id: 1,
    location: "Moyale, Kenya",
    rate_min: 600,
    rate_max: 1200,
    negotiability: true,
  },
];

export const counties = [
  { id: "1", name: "Mombasa" },
  { id: "2", name: "Kwale" },
  { id: "3", name: "Kilifi" },
  { id: "4", name: "Tana River" },
  { id: "5", name: "Lamu" },
  { id: "6", name: "Taita/Taveta" },
  { id: "7", name: "Garissa" },
  { id: "8", name: "Wajir" },
  { id: "9", name: "Mandera" },
  { id: "10", name: "Marsabit" },
  { id: "11", name: "Isiolo" },
  { id: "12", name: "Meru" },
  { id: "13", name: "Tharaka-Nithi" },
  { id: "14", name: "Embu" },
  { id: "15", name: "Kitui" },
  { id: "16", name: "Machakos" },
  { id: "17", name: "Makueni" },
  { id: "18", name: "Nyandarua" },
  { id: "19", name: "Nyeri" },
  { id: "20", name: "Kirinyaga" },
  { id: "21", name: "Murang'a" },
  { id: "22", name: "Kiambu" },
  { id: "23", name: "Turkana" },
  { id: "24", name: "West Pokot" },
  { id: "25", name: "Samburu" },
  { id: "26", name: "Trans Nzoia" },
  { id: "27", name: "Uasin Gishu" },
  { id: "28", name: "Elgeyo Marakwet" },
  { id: "29", name: "Nandi" },
  { id: "30", name: "Baringo" },
  { id: "31", name: "Laikipia" },
  { id: "32", name: "Nakuru" },
  { id: "33", name: "Narok" },
  { id: "34", name: "Kajiado" },
  { id: "35", name: "Kericho" },
  { id: "36", name: "Bomet" },
  { id: "37", name: "Kakamega" },
  { id: "38", name: "Vihiga" },
  { id: "39", name: "Bungoma" },
  { id: "40", name: "Busia" },
  { id: "41", name: "Siaya" },
  { id: "42", name: "Kisumu" },
  { id: "43", name: "Homa Bay" },
  { id: "44", name: "Migori" },
  { id: "45", name: "Kisii" },
  { id: "46", name: "Nyamira" },
  { id: "47", name: "Nairobi City" },
];
